exports.dbConfig={
    server:"LAPTOP-P4D7V446\\SQLEXPRESS",
    database:"Project",
    user:"tejasp",
    password:"tejasp@2000",
    port:1433
};
exports.webPort=9000;
exports.httpMsgsFormat="HTML";